### PR TITLE
Added openstreetmap

### PR DESCRIPTION
**Pull request by jaytaph**

### CODE REVIEW

**Comment by juokaz** [comment]
There is also #16 you guys should somehow collaborate :)

**Comment by jaytaph** [comment]
If only we had a relay chat over the internet.. that would really be
lovely :-)

Juozas Joe Kaziukėnas wrote:

**Comment by juokaz** [comment]
I comment here because it's persisted and will be stored together with a pull request :)

**Comment by jaytaph** [comment]
Closing this request and mergingw with dericks

**Pull request closed without merging**
