### PR TITLE
Working with issue #50 and completing the Hotels section.

### PR DESCRIPTION
**Pull request by dragoonis**
- Second phase of styling to come, but it is acceptable and functional

### CODE REVIEW

**Comment by juokaz** [comment]
1. We have a javascript file, js/whiskyweb.js, please put logic there rather than inline js.
2. There is img/ folder, put images there rather than css/images.

**Comment by dragoonis** [comment]
1. There was already mapping code in there for the OSM (The Hub), will try to move it all inline.
2. What is css/images for? I was just trying to copy what was already there.

**Comment by juokaz** [comment]
1. There was only mapping code there, which was kind of ok. Now there is way too much there.
2. I don't know, Derick put map images there, but they shouldn't be there at all. Not really important for this, above images should be in /img.

**Comment by dragoonis** [comment]
1 is done.
2 is done.

Commit hash: https://github.com/dragoonis/whiskyweb-website/commit/f8412282093f1d2affc31f41fca4f7074756def8

**Comment by dragoonis** [comment]
UI Improvements: https://github.com/dragoonis/whiskyweb-website/commit/23bfabe7a65ce9958c1d152941bdc7096a521e12

**Comment by juokaz** [comment]
Map marker is poorly sized. Lets fix that and launch.

**Comment by dragoonis** [comment]
Yes, I believe max put that in there, I noticed it was squished but i
couldn't see where he specified dimensions of the icon,

can someone with OSM experience point me in the right direction to
fixing this? @maxmanders? @mgdm?
- Paul.

On Thu, Feb 23, 2012 at 11:45 AM, Juozas Joe Kaziukėnas
reply@reply.github.com
wrote:

**Comment by dragoonis** [comment]
Looks like this will fix it, stole it from TheHub icon :)

`iconSize: new L.Point(71, 73),`

I'll play with the dimensions and re-commit

**Pull request merged**
