### PR TITLE
Added an OSM map.

### PR DESCRIPTION
**Pull request by derickr**
Hi!

This adds the basic map. After you've laid it out and added text I'll come around and update it with links to routing and the proper icon.

cheers,
Derick

### CODE REVIEW

**Comment by juokaz** [comment]
This is a fix for issue #10

**Comment by juokaz** [comment]
There is also a map at the bottom of the page (http://webspecies.github.com/whiskyweb-website/#tickets), which also has <div id="map"></div> I assume this will brake, no?

**Comment by derickr** [comment]
I've updated it for two maps; but do you really need a "how to get to the conference?" section there as well?

**Comment by derickr** [comment]
Also, you do _not_ want the really heavy OpenLayers. Leaflet is much lighter.

**Comment by juokaz** [comment]
pull request #18 tries to fix this

**Comment by juokaz** [comment]
Closed with #18

**Pull request closed without merging**
